extends: airbnb
plugins:
  - import
  - 
env:
  browser: true
  node: true
  es6: true
  shared-node-browser: true
globals:
  __DEV__: false
settings:
  import/extensions:
        - .js
  import/resolver:
    webpack:
      config: webpack.config.js
parserOptions:
  ecmaVersion: 6
  sourceType: module,
  ecmaFeatures:
    jsx: true
rules:
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 1
  import/extensions: 1
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/href-no-hash: 0
  react/prop-types: 2
  no-unused-expressions: 0
  react/jsx-filename-extension: 0
  react/jsx-no-bind: 0
  no-plusplus: 0
  react/forbid-prop-types: 0
  space-before-function-paren: [
    2,
    always,
  ]
  no-restricted-syntax: 0
  dot-notation: 0
  import/no-webpack-loader-syntax: 0
  import/first: 0
  global-require: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  import/prefer-default-export: 1
  react/no-array-index-key: 1
  no-confusing-arrow: 1
  standard/computed-property-even-spacing: [1, even]
  no-console: error
  comma-dangle: [error, never],
  max-len: [error, 120],
  one-var: [error, {uninitialized: always, initialized: never}],
  one-var-declaration-per-line: [error, initializations],
  filenames/match-regex: [error, ^[a-z0-9\\-\\.]+$],
  new-cap: [error, {capIsNewExceptions: [Map]}],
  yoda: [error, always],
  handle-callback-err: error,
  object-curly-spacing: [error, never],
  import/prefer-default-export: off,
  arrow-parens: [error, as-needed],
  global-require: off,
  func-style: [error, declaration],
  func-names: error,
  no-underscore-dangle: [error, {allow: [_links, _embedded]}],
  no-unused-vars: [error, {ignoreRestSiblings: true}],
  no-multi-spaces: [error, {ignoreEOLComments: true}],
  eslint-comments/disable-enable-pair: error,
  eslint-comments/no-duplicate-disable: error,
  eslint-comments/no-unlimited-disable: error,
  eslint-comments/no-unused-disable: error,
  eslint-comments/no-unused-enable: error
